### ISSUE TITLE
Overriding instance method must be as accessible as its enclosing type

### ISSUE THREAD

**Issue by dagio** [bignerdranch/Deferred#141]
Hi there

Have you try to build on Xcode 8.1 ? I have no problem running tests on the repository using Xcode 8.1 but when using the pods I run into this compilation error.

<img width="1100" alt="screen shot 2016-10-28 at 22 45 15" src="https://cloud.githubusercontent.com/assets/74581/19821732/4ca16f44-9d60-11e6-8a81-8e54c09f48e0.png">

**Comment by zwaldowski** [comment]
This has already been fixed on the `swift-3_0` branch, from which we're planning to cut a new beta very soon.
